INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [06/Nov/2023 18:20:14] "POST /new_request HTTP/1.1" 200 -
DEBUG:root:Sending request to container0 with data: {'key1': 'value1', 'key2': 'value2'}...
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 52.23.176.37:5000
DEBUG:root:An error occurred when sending request to container0: HTTPConnectionPool(host='52.23.176.37', port=5000): Max retries exceeded with url: /path_to_worker_endpoint (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000017ACAD1BED0>, 'Connection to 52.23.176.37 timed out. (connect timeout=None)'))
DEBUG:root:Checking if there are any requests in the queue...
INFO:werkzeug:127.0.0.1 - - [06/Nov/2023 18:21:27] "POST /new_request HTTP/1.1" 200 -
DEBUG:root:Sending request to container0 with data: {'key1': 'value1', 'key2': 'value2'}...
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 52.23.176.37:5000
INFO:werkzeug:127.0.0.1 - - [06/Nov/2023 18:21:38] "POST /new_request HTTP/1.1" 200 -
DEBUG:root:Sending request to container1 with data: {'key1': 'value1', 'key2': 'value2'}...
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 52.23.176.37:5001
INFO:werkzeug:127.0.0.1 - - [06/Nov/2023 18:21:41] "POST /new_request HTTP/1.1" 200 -
DEBUG:root:Sending request to container2 with data: {'key1': 'value1', 'key2': 'value2'}...
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 54.197.74.27:5000
DEBUG:root:An error occurred when sending request to container0: HTTPConnectionPool(host='52.23.176.37', port=5000): Max retries exceeded with url: /path_to_worker_endpoint (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000017ACAD2C2D0>, 'Connection to 52.23.176.37 timed out. (connect timeout=None)'))
DEBUG:root:Checking if there are any requests in the queue...
DEBUG:root:An error occurred when sending request to container1: HTTPConnectionPool(host='52.23.176.37', port=5001): Max retries exceeded with url: /path_to_worker_endpoint (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000017ACAD24150>, 'Connection to 52.23.176.37 timed out. (connect timeout=None)'))
DEBUG:root:Checking if there are any requests in the queue...
DEBUG:root:An error occurred when sending request to container2: HTTPConnectionPool(host='54.197.74.27', port=5000): Max retries exceeded with url: /path_to_worker_endpoint (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000017ACAD38D50>, 'Connection to 54.197.74.27 timed out. (connect timeout=None)'))
DEBUG:root:Checking if there are any requests in the queue...
INFO:werkzeug:127.0.0.1 - - [06/Nov/2023 18:23:28] "POST /new_request HTTP/1.1" 200 -
DEBUG:root:Sending request to container0 with data: {'key1': 'value1', 'key2': 'value2'}...
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 52.23.176.37:5000
INFO:werkzeug:127.0.0.1 - - [06/Nov/2023 18:23:28] "POST /new_request HTTP/1.1" 200 -
DEBUG:root:Sending request to container1 with data: {'key1': 'value1', 'key2': 'value2'}...
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 52.23.176.37:5001
INFO:werkzeug:127.0.0.1 - - [06/Nov/2023 18:23:29] "POST /new_request HTTP/1.1" 200 -
DEBUG:root:Sending request to container2 with data: {'key1': 'value1', 'key2': 'value2'}...
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 54.197.74.27:5000
INFO:werkzeug:127.0.0.1 - - [06/Nov/2023 18:23:30] "POST /new_request HTTP/1.1" 200 -
DEBUG:root:Sending request to container3 with data: {'key1': 'value1', 'key2': 'value2'}...
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 54.197.74.27:5001
INFO:werkzeug:127.0.0.1 - - [06/Nov/2023 18:23:30] "POST /new_request HTTP/1.1" 200 -
DEBUG:root:Sending request to container4 with data: {'key1': 'value1', 'key2': 'value2'}...
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 18.212.161.72:5000
INFO:werkzeug:127.0.0.1 - - [06/Nov/2023 18:23:31] "POST /new_request HTTP/1.1" 200 -
DEBUG:root:Sending request to container5 with data: {'key1': 'value1', 'key2': 'value2'}...
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 18.212.161.72:5001
INFO:werkzeug:127.0.0.1 - - [06/Nov/2023 18:23:32] "POST /new_request HTTP/1.1" 200 -
DEBUG:root:Sending request to container6 with data: {'key1': 'value1', 'key2': 'value2'}...
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 35.171.19.86:5000
INFO:werkzeug:127.0.0.1 - - [06/Nov/2023 18:23:33] "POST /new_request HTTP/1.1" 200 -
DEBUG:root:Sending request to container7 with data: {'key1': 'value1', 'key2': 'value2'}...
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 35.171.19.86:5001
INFO:werkzeug:127.0.0.1 - - [06/Nov/2023 18:23:33] "POST /new_request HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Nov/2023 18:23:34] "POST /new_request HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Nov/2023 18:23:35] "POST /new_request HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Nov/2023 18:23:36] "POST /new_request HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Nov/2023 18:23:36] "POST /new_request HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Nov/2023 18:23:37] "POST /new_request HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Nov/2023 18:23:38] "POST /new_request HTTP/1.1" 200 -
DEBUG:root:An error occurred when sending request to container0: HTTPConnectionPool(host='52.23.176.37', port=5000): Max retries exceeded with url: /path_to_worker_endpoint (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000017ACAD3B790>, 'Connection to 52.23.176.37 timed out. (connect timeout=None)'))
DEBUG:root:Checking if there are any requests in the queue...
DEBUG:root:Found requests in the queue, processing the first one...
DEBUG:root:An error occurred when sending request to container1: HTTPConnectionPool(host='52.23.176.37', port=5001): Max retries exceeded with url: /path_to_worker_endpoint (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000017ACAD382D0>, 'Connection to 52.23.176.37 timed out. (connect timeout=None)'))
DEBUG:root:An error occurred when sending request to container2: HTTPConnectionPool(host='54.197.74.27', port=5000): Max retries exceeded with url: /path_to_worker_endpoint (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000017ACAD2D5D0>, 'Connection to 54.197.74.27 timed out. (connect timeout=None)'))
DEBUG:root:An error occurred when sending request to container3: HTTPConnectionPool(host='54.197.74.27', port=5001): Max retries exceeded with url: /path_to_worker_endpoint (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000017ACAD27E90>, 'Connection to 54.197.74.27 timed out. (connect timeout=None)'))
DEBUG:root:An error occurred when sending request to container4: HTTPConnectionPool(host='18.212.161.72', port=5000): Max retries exceeded with url: /path_to_worker_endpoint (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000017ACAD482D0>, 'Connection to 18.212.161.72 timed out. (connect timeout=None)'))
DEBUG:root:An error occurred when sending request to container5: HTTPConnectionPool(host='18.212.161.72', port=5001): Max retries exceeded with url: /path_to_worker_endpoint (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000017ACAD4BA10>, 'Connection to 18.212.161.72 timed out. (connect timeout=None)'))
DEBUG:root:An error occurred when sending request to container6: HTTPConnectionPool(host='35.171.19.86', port=5000): Max retries exceeded with url: /path_to_worker_endpoint (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000017ACAD563D0>, 'Connection to 35.171.19.86 timed out. (connect timeout=None)'))
DEBUG:root:An error occurred when sending request to container7: HTTPConnectionPool(host='35.171.19.86', port=5001): Max retries exceeded with url: /path_to_worker_endpoint (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000017ACAD5AF10>, 'Connection to 35.171.19.86 timed out. (connect timeout=None)'))
